In [1]:
import warnings
warnings.filterwarnings( 'ignore' )

import gc
import os
import time
import numpy as np
import pandas as pd

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold, train_test_split

import tensorflow as tf
from tensorflow.keras import backend as K
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import text, sequence

from contextlib import redirect_stdout
from tensorflow.keras.utils import plot_model

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' # supress tensorflow warnings

os.environ["CUDA_VISIBLE_DEVICES"] = "1"

In [2]:
import All_UT_Models
import UT_Utils

In [3]:
# hyper parameters for this model

MAX_LEN = 100
EMBED_SIZE = 300
PRE_TRAINED_FLAG = True
EMBED_TRAINABLE = False

EMB_WEIGHTS_INIT = 'he_normal'
DRPT = 0.4
CONV_WEIGHTS_INIT = 'he_uniform'
CONV_ACT = 'elu'
FC_WEIGHTS_INIT = 'he_uniform'
FC_ACT = 'elu'
LR_RATE = 1e-3
OPTIMIZER = 'adam'

BATCH = 32
NEPOCHS = 30
PATIENCE = 5
DECAY = True
DECAY_RATE = 0.3
DECAY_AFTER = 1

In [4]:
#EMBEDDING_FILE = './Embeddings/urduvec_140M_100K_300d.txt'
EMBEDDING_FILE = './Embeddings/cc.ur.300.vec'

EMBEDDING_MATRIX = []

modelname = 'MCBiGRU-ft'

modelpath = './Saved Models/' + modelname + '/'
modelresults = './Model Results'
modelsummaries = './Model - Summaries-Figures'

DIRECTORIES_TO_BE_CREATED = [ modelpath, modelresults, modelsummaries ]
for directory in DIRECTORIES_TO_BE_CREATED:
    if not os.path.exists( directory ):
        os.makedirs( directory )

In [5]:
def hms_string( sec_elapsed ):
    h = int(sec_elapsed / (60 * 60))
    m = int((sec_elapsed % (60 * 60)) / 60)
    s = sec_elapsed % 60
    return "{} hrs {:>02} mins {:>05.2f} secs".format( h, m, s )

In [6]:
sheets = [ pd.read_excel( 'RUT_UT_Comments.xlsx', 'Sheet1' ), pd.read_excel( 'RUT_UT_Comments.xlsx', 'Sheet2' ) ]
df = pd.concat( sheets )
df.reset_index( drop=True, inplace=True )

df.Urdu = df.Urdu.astype( 'str' )
df.Urdu = df.Urdu.apply( UT_Utils.urdu_preprocessing )

df.dropna( inplace=True )
df.reset_index( drop=True, inplace=True )

del sheets
gc.collect()

xcolumn = 'Urdu'
ycolumn = 'Toxic'

df.shape

(72771, 3)

In [7]:
def get_coefs( word, *arr ):
    return word, np.asarray( arr, dtype='float32' )

def get_vectors( tokenizer, emb_mean, emb_std, embed_size ):
    hits = 0
    misses = 0
    word_index = tokenizer.word_index
    num_words = len( word_index ) + 1
    embedding_matrix = np.random.normal( emb_mean, emb_std, ( num_words, embed_size ) ) # for unk tokens
    embedding_matrix[0] = np.zeros( ( embed_size ) ) # replace zero padding with zeros
    for word, i in word_index.items(  ):
        embedding_vector = EMBEDDINGS_INDEX.get( word )
        if embedding_vector is not None:
            embedding_matrix[ i ] = embedding_vector
            hits += 1
        else:
            misses += 1
    print( "Pretrained Embeddings: %d hits (%d misses)" % ( hits, misses ) )
    gc.collect()
    return embedding_matrix

if PRE_TRAINED_FLAG == True:
    EMBEDDINGS_INDEX = dict( get_coefs( *o.strip().split() ) for o in open( EMBEDDING_FILE, encoding='utf-8' )  if len(o)>19 )
    print( 'Total Words in Pretrained Embeddings: ', len( EMBEDDINGS_INDEX.values() ) )
    all_embs = np.stack( EMBEDDINGS_INDEX.values() )
    emb_mean, emb_std = all_embs.mean(), all_embs.std()
    print( 'Pretrained Embeddings mean:', emb_mean, ' std: ', emb_std )

Total Words in Pretrained Embeddings:  1153999
Pretrained Embeddings mean: -0.00027458658  std:  0.024344679


In [8]:
skf = StratifiedKFold( n_splits=5, random_state=0, shuffle=True )
print(skf)

StratifiedKFold(n_splits=5, random_state=0, shuffle=True)


In [9]:
warnings.filterwarnings( 'ignore' )
start_time = time.time()
print( 'Local System Time: {}'.format( time.strftime( "%I:%M %p", time.localtime() ) ) )

valaccuracy, valprecision, valrecall, valf1, valcm = [], [], [], [], []
testaccuracy, testprecision, testrecall, testf1, testcm = [], [], [], [], []
com_text, com_label, com_predicted, com_prob = [], [], [], []
com_indices = []
hist = {}

fold = 1
for train_index, test_index in skf.split( df[ xcolumn ], df[ ycolumn ] ):
    # seprating train and test sets
    xtrain = df.loc[ train_index ][ xcolumn ].values
    xtest = df.loc[ test_index ][ xcolumn ].values
    
    ytrain = df.loc[ train_index ][ ycolumn ].values
    ytest = df.loc[ test_index ][ ycolumn ].values
    
    # splitting train and validation sets
    xtrain, xval, ytrain, yval = train_test_split( xtrain, ytrain, test_size=0.15, random_state=0 )
    
    # tokenization with keras tokenizer
    tokenizer = text.Tokenizer(  )
    tokenizer.fit_on_texts( np.append( xtrain, xval ) )

    xtrain = tokenizer.texts_to_sequences( xtrain )
    xval = tokenizer.texts_to_sequences( xval )
    xtest = tokenizer.texts_to_sequences( xtest )
    
    # pad the tokenized sequences
    xtrain = sequence.pad_sequences( xtrain, maxlen=MAX_LEN )
    xval = sequence.pad_sequences( xval, maxlen=MAX_LEN )
    xtest = sequence.pad_sequences( xtest, maxlen=MAX_LEN )
    
    # check if pre-trained word embeddings flag is true
    if PRE_TRAINED_FLAG == True:
        EMBEDDING_MATRIX = get_vectors(
            tokenizer=tokenizer, emb_mean=emb_mean, emb_std=emb_std, embed_size=EMBED_SIZE
        )
    
    # define a model
    EMBED_INP_SIZE = len( tokenizer.word_index ) + 1
    model = All_UT_Models.MCBiGRU(
        max_len=MAX_LEN, embed_inp=EMBED_INP_SIZE, embed_size=EMBED_SIZE,
        embedding_matrix=EMBEDDING_MATRIX, embed_trainable=EMBED_TRAINABLE,
        drpt=DRPT, emb_weights_init=EMB_WEIGHTS_INIT,
        conv_weights_init=CONV_WEIGHTS_INIT, conv_act=CONV_ACT,
        fc_weights_init=FC_WEIGHTS_INIT, fc_act=FC_ACT, optimizer=OPTIMIZER
    )
    
    # save model summaries and model architecture diagrams in the first fold only
    if fold == 1:
        plot_model( model=model, to_file='{}/{}.png'.format( modelsummaries, modelname ), show_shapes=False )
        
        with open( '{}/{}.txt'.format( modelsummaries, modelname ), 'w' ) as s:
            with redirect_stdout( s ):
                model.summary()
    
    K.set_value( model.optimizer.lr, LR_RATE )
    
    # train the model with callbacks for early stopping
    f1callback = UT_Utils.F1_score_callback(
        val_data=( xval, yval ), filepath=modelpath + modelname + str( fold ),
        patience=PATIENCE, decay=DECAY, decay_rate=DECAY_RATE, decay_after=DECAY_AFTER
    )
    histmodel = model.fit(
        xtrain, ytrain, batch_size=BATCH, epochs=NEPOCHS, verbose=0, callbacks=[ f1callback ]
    )
    
    # save history of all folds
    hist[ 'fold' + str( fold ) ] = histmodel.history.copy()
    
    # delete trained model object
    del model, histmodel, f1callback
    EMBEDDING_MATRIX = []
    K.clear_session()
    gc.collect()
    # delete pre trained embeddings from the memory
    if ( PRE_TRAINED_FLAG == True ) and ( fold == skf.n_splits ):
        del EMBEDDINGS_INDEX
        gc.collect()
    
    # load saved model
    loaded_model = load_model( modelpath + modelname + str( fold ) )
    
    # get predictions (probabilities) for validation and test sets respectively
    valpredictions = loaded_model.predict( xval, verbose=0, batch_size=BATCH )
    testpredictions = loaded_model.predict( xtest, verbose=0, batch_size=BATCH )
    
    # delete loaded model
    del loaded_model
    K.clear_session()
    gc.collect()
    
    # optimizer threshold on validation set
    threshold = UT_Utils.optimize_threshold( yval, valpredictions )
    
    # save accuracy, precision, recall, f1 and confusion matrices
    vallabels = ( valpredictions >= threshold ).astype( 'int32' )
    testlabels = ( testpredictions >= threshold ).astype( 'int32' )
    
    valaccuracy.append( accuracy_score( yval, vallabels ) )
    valprecision.append( precision_score( yval, vallabels ) )
    valrecall.append( recall_score( yval, vallabels ) )
    valf1.append( f1_score( yval, vallabels ) )
    valcm.append( confusion_matrix( yval, vallabels ) )    
    
    testaccuracy.append( accuracy_score( ytest, testlabels ) )
    testprecision.append( precision_score( ytest, testlabels ) )
    testrecall.append( recall_score( ytest, testlabels ) )
    testf1.append( f1_score( ytest, testlabels ) )
    testcm.append( confusion_matrix( ytest, testlabels ) )
    
    # save for future analysis and ensemble
    com_indices.extend( test_index.tolist() )
    com_text.extend( df.loc[ test_index ][ xcolumn ] )
    com_label.extend( df.loc[ test_index ][ ycolumn ].tolist() )
    com_predicted.extend( testlabels[:,0].tolist() )
    com_prob.extend( testpredictions[:,0].tolist() )
    
    print( 'Fold: {:02d} out of {:02d} completed.'.format( fold, skf.get_n_splits() ) )
    print( 'Local System Time: {}'.format( time.strftime( "%I:%M %p", time.localtime() ) ) )
    
    fold = fold + 1
time_took = time.time() - start_time
print( f"Total runtime: { hms_string( time_took ) }" )

Local System Time: 12:46 AM
Pretrained Embeddings: 28830 hits (16914 misses)
Epoch: 001 --LR: 1e-03 --MaxValF1: 0.7483281 --CurValF1: 0.7483281 --Patience: 01 --F1 improved: 0.7483281
Epoch: 002 --LR: 1e-03 --MaxValF1: 0.8154214 --CurValF1: 0.8154214 --Patience: 01 --F1 improved: 0.8154214
Epoch: 003 --LR: 1e-03 --MaxValF1: 0.8299830 --CurValF1: 0.8299830 --Patience: 01 --F1 improved: 0.8299830
Epoch: 004 --LR: 1e-03 --MaxValF1: 0.8333333 --CurValF1: 0.8333333 --Patience: 01 --F1 improved: 0.8333333
Epoch: 005 --LR: 1e-03 --MaxValF1: 0.8394329 --CurValF1: 0.8394329 --Patience: 01 --F1 improved: 0.8394329
Epoch: 006 --LR: 1e-03 --MaxValF1: 0.8394329 --CurValF1: 0.8382993 --Patience: 01
Epoch: 007 --LR: 3e-04 --MaxValF1: 0.8394329 --CurValF1: 0.8318821 --Patience: 02
Epoch: 008 --LR: 9e-05 --MaxValF1: 0.8394329 --CurValF1: 0.8355401 --Patience: 03
Epoch: 009 --LR: 3e-05 --MaxValF1: 0.8394329 --CurValF1: 0.8366782 --Patience: 04
Epoch: 010 --LR: 8e-06 --MaxValF1: 0.8394329 --CurValF1: 0.8

In [10]:
print( 'Validation Accuracy' )
print( [ '{:0.4f}'.format( x ) for x in valaccuracy ], np.mean( valaccuracy ), '+-', np.std( valaccuracy ), '\n' )

print( 'Validation Precision' )
print( [ '{:0.4f}'.format( x ) for x in valprecision ], np.mean( valprecision ), '+-', np.std( valprecision ), '\n' )

print( 'Validation Recall' )
print( [ '{:0.4f}'.format( x ) for x in valrecall ], np.mean( valrecall ), '+-', np.std( valrecall ), '\n' )

print( 'Validation F1' )
print( [ '{:0.4f}'.format( x ) for x in valf1 ], np.mean( valf1 ), '+-', np.std( valf1 ) )

Validation Accuracy
['0.9442', '0.9472', '0.9454', '0.9523', '0.9488'] 0.9475781518378564 +- 0.002810843649159033 

Validation Precision
['0.8498', '0.8722', '0.8682', '0.9030', '0.8709'] 0.8728434028039622 +- 0.017127330957547298 

Validation Recall
['0.8293', '0.8207', '0.8135', '0.8168', '0.8330'] 0.8226533156392006 +- 0.007399570663576532 

Validation F1
['0.8394', '0.8457', '0.8400', '0.8577', '0.8515'] 0.8468712216338418 +- 0.006984051106556505


In [11]:
for c in valcm:
    print( np.rot90(np.rot90(c)), '\n' )

[[1273  262]
 [ 225 6973]] 

[[1263  276]
 [ 185 7009]] 

[[1252  287]
 [ 190 7004]] 

[[1257  282]
 [ 135 7059]] 

[[1282  257]
 [ 190 7004]] 



In [12]:
print( 'Test Accuracy' )
print( [ '{:0.4f}'.format( x ) for x in testaccuracy ], np.mean( testaccuracy ), '+-', np.std( testaccuracy ), '\n' )

print( 'Test Precision' )
print( [ '{:0.4f}'.format( x ) for x in testprecision ], np.mean( testprecision ), '+-', np.std( testprecision ), '\n' )

print( 'Test Recall' )
print( [ '{:0.4f}'.format( x ) for x in testrecall ], np.mean( testrecall ), '+-', np.std( testrecall ), '\n' )

print( 'Test F1' )
print( [ '{:0.4f}'.format( x ) for x in testf1 ], np.mean( testf1 ), '+-', np.std( testf1 ) )

Test Accuracy
['0.9465', '0.9470', '0.9498', '0.9464', '0.9481'] 0.9475615435086816 +- 0.0012836427085805156 

Test Precision
['0.8799', '0.8876', '0.8937', '0.9049', '0.8922'] 0.8916671856363767 +- 0.008172736198326334 

Test Recall
['0.8137', '0.8080', '0.8186', '0.7847', '0.8091'] 0.8068253718422916 +- 0.011708902840810208 

Test F1
['0.8455', '0.8460', '0.8545', '0.8405', '0.8486'] 0.8470230710844732 +- 0.004579341253596524


In [13]:
for c in testcm:
    print( np.rot90(np.rot90(c)), '\n' )

[[ 2132   488]
 [  291 11644]] 

[[ 2117   503]
 [  268 11666]] 

[[ 2144   475]
 [  255 11680]] 

[[ 2055   564]
 [  216 11719]] 

[[ 2119   500]
 [  256 11679]] 



In [14]:
file = open( '{}/ResultsMain.csv'.format( modelresults ), mode='a' )
file.write( modelname )
file.write( ',' )
file.write( str(np.mean( testaccuracy ))[:7] + '+-' + str(np.std( testaccuracy ))[:6] )
file.write( ',' )
file.write( str(np.mean( testprecision ))[:7] + '+-' + str(np.std( testprecision ))[:6] )
file.write( ',' )
file.write( str(np.mean( testrecall ))[:7] + '+-' + str(np.std( testrecall ))[:6] )
file.write( ',' )
file.write( str(np.mean( testf1 ))[:7] + '+-' + str(np.std( testf1 ))[:6] )
file.write( '\n' )
file.close()

In [15]:
dfPredictions = pd.DataFrame(  )
dfPredictions[ 'comment_indices' ] = com_indices
#dfPredictions[ 'comment_text' ] = com_text #comment text
dfPredictions[ 'comment_label' ] = com_label
dfPredictions[ 'comment_predicted' ] = com_predicted
dfPredictions[ 'comment_prob' ] = com_prob
dfPredictions.to_csv( '{}/{}.csv'.format( modelresults, modelname ), index=False )
dfPredictions.shape

(72771, 4)